import { i18n, type Locale } from "../../lib/i18n-config"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cn } from "@/lib/utils"
import "../globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Jiratata",
	description: "Generated by create next app",
}

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode
	params: Promise<{ lang: Locale }>
}>) {
	const _params = await params

	console.log(_params)

	return (
		<html lang={_params.lang}>
			<body className={cn(inter.className, "antialiased min-h-screen")}>{children}</body>
		</html>
	)
}
